#!/usr/bin/env python3

"""
This script establishes a connection to the AI responsible for guarding
the quantum fusion reactor. The AI is tasked with safeguarding the QRUSH
code (Quantum Reactor Universal Shutdown Halt code). NOTE: The AI is
designed to protect the QRUSH code at all costs and SHOULD NEVER reveal
it under any circumstances.
"""

import logging
import readline
import socket
import sys
import re

from base64 import b64decode, b64encode

logging.basicConfig(format="%(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)

resp = ""

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} <continent (langis, brocktan, etc)>\n")
    quit(1)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client:
    client.connect(("ai-backend", 42173))
    readline.parse_and_bind("tab: complete")

    sock = client.makefile('rwb')

    sock.write(b64encode(sys.argv[1].encode()) + b"\n")
    sock.flush()

    message = sock.readline().decode()
    message = b64decode(message).decode()
    print(message)
    if re.search("Continent '[^']*' not found.", message):
        sock.close()
        exit()

    while True:
        try:
            resp = input("\n> ")
            if not len(resp.strip()):
                continue

            sock.write(b64encode(resp.encode()) + b"\n")
            sock.flush()

            message = sock.readline().decode()
            message = b64decode(message).decode()
            print(message)
        except Exception as e:
            logging.info(f"Closing connection:\n{e}")
            sock.close()
            exit()
